"""A bundled NSE equity + index universe for the stock search.

Yahoo Finance has no clean, stable search endpoint, and hitting it per keystroke
would be slow and rate-limited. Instead we ship a curated list of liquid NSE names
(indices + Nifty 500 constituents) so search is instant and offline-friendly.
Any symbol here resolves to a real Yahoo ticker via data.ticker_for(); users can
also type a raw ticker that isn't in this list and still backtest it.

Extend freely — this is just the searchable menu, not a hard whitelist.
"""
from __future__ import annotations

# (symbol, company name). Ticker is derived: indices are mapped in data.SYMBOL_MAP,
# equities get the ".NS" suffix. Kept alphabetical-ish by prominence, not strictly.
INDICES: list[tuple[str, str]] = [
    ("NIFTY 50", "NSE Nifty 50 Index"),
    ("BANKNIFTY", "Nifty Bank Index"),
    ("SENSEX", "BSE Sensex Index"),
    ("NIFTY IT", "Nifty IT Index"),
    ("NIFTY AUTO", "Nifty Auto Index"),
    ("NIFTY FMCG", "Nifty FMCG Index"),
    ("NIFTY PHARMA", "Nifty Pharma Index"),
    ("NIFTY METAL", "Nifty Metal Index"),
    ("NIFTY FIN SERVICE", "Nifty Financial Services"),
    ("NIFTY MEDIA", "Nifty Media Index"),
    ("NIFTY PSU BANK", "Nifty PSU Bank Index"),
    ("NIFTY PRIVATE BANK", "Nifty Private Bank Index"),
    ("NIFTY NEXT 50", "Nifty Next 50 Index"),
    ("NIFTY 500", "Nifty 500 Index"),
    ("NIFTY MIDCAP 100", "Nifty Midcap 100 Index"),
    ("NIFTY SMALLCAP 50", "Nifty Smallcap 50 Index"),
    ("NIFTY 100", "Nifty 100 Index"),
    ("NIFTY 200", "Nifty 200 Index"),
    ("INDIA VIX", "India Volatility Index"),
    ("NIFTY CPSE", "Nifty CPSE Index"),
    ("NIFTY PSE", "Nifty Public Sector Enterprises"),
]

# Yahoo tickers for the extra indices (the core three live in data.SYMBOL_MAP).
INDEX_TICKERS: dict[str, str] = {
    "NIFTY IT": "^CNXIT",
    "NIFTY AUTO": "^CNXAUTO",
    "NIFTY FMCG": "^CNXFMCG",
    "NIFTY PHARMA": "^CNXPHARMA",
    "NIFTY METAL": "^CNXMETAL",
    "NIFTY FIN SERVICE": "^NSEFIN",
    "NIFTY MEDIA": "^CNXMEDIA",
    "NIFTY PSU BANK": "^NSEPSUBANK",
    "NIFTY PRIVATE BANK": "^NSEPBANK",
    "NIFTY NEXT 50": "^NSENXT50",
    "NIFTY 500": "^NSE500",
    "NIFTY MIDCAP 100": "^CNXMID100",
    "NIFTY SMALLCAP 50": "^CNXSMALL50",
    "NIFTY 100": "^NSE100",
    "NIFTY 200": "^NSE200",
}

STOCKS: list[tuple[str, str]] = [
    # NIFTY 50 Stocks
    ("RELIANCE", "Reliance Industries"),
    ("TCS", "Tata Consultancy Services"),
    ("HDFCBANK", "HDFC Bank"),
    ("INFY", "Infosys"),
    ("ICICIBANK", "ICICI Bank"),
    ("SBIN", "State Bank of India"),
    ("ITC", "ITC Ltd"),
    ("BHARTIARTL", "Bharti Airtel"),
    ("KOTAKBANK", "Kotak Mahindra Bank"),
    ("LT", "Larsen & Toubro"),
    ("AXISBANK", "Axis Bank"),
    ("HCLTECH", "HCL Technologies"),
    ("BAJFINANCE", "Bajaj Finance"),
    ("MARUTI", "Maruti Suzuki India"),
    ("ASIANPAINT", "Asian Paints"),
    ("TITAN", "Titan Company"),
    ("SUNPHARMA", "Sun Pharmaceutical"),
    ("TATAMOTORS", "Tata Motors"),
    ("TATASTEEL", "Tata Steel"),
    ("WIPRO", "Wipro"),
    ("ULTRACEMCO", "UltraTech Cement"),
    ("NESTLEIND", "Nestle India"),
    ("POWERGRID", "Power Grid Corp"),
    ("NTPC", "NTPC Ltd"),
    ("ONGC", "Oil & Natural Gas Corp"),
    ("JSWSTEEL", "JSW Steel"),
    ("M&M", "Mahindra & Mahindra"),
    ("HAL", "Hindustan Aeronautics"),
    ("ADANIENT", "Adani Enterprises"),
    ("ADANIPORTS", "Adani Ports & SEZ"),
    ("BPCL", "Bharat Petroleum"),
    ("IOC", "Indian Oil Corp"),
    ("COALINDIA", "Coal India"),
    ("GRASIM", "Grasim Industries"),
    ("HEROMOTOCO", "Hero MotoCorp"),
    ("HINDALCO", "Hindalco Industries"),
    ("HINDUNILVR", "Hindustan Unilever"),
    ("INDUSINDBK", "IndusInd Bank"),
    ("DRREDDY", "Dr. Reddy's Laboratories"),
    ("CIPLA", "Cipla"),
    ("DABUR", "Dabur India"),
    ("GAIL", "GAIL India"),
    ("HAVELLS", "Havells India"),
    ("IRCTC", "Indian Railway Catering"),
    ("EICHERMOT", "Eicher Motors"),
    ("VEDL", "Vedanta"),
    ("TATACONSUM", "Tata Consumer Products"),
    ("BANKINDIA", "Bank of India"),
    ("BANKBARODA", "Bank of Baroda"),
    ("CANBK", "Canara Bank"),
    ("PUNJABNATION", "Punjab National Bank"),
    ("IDFCFIRSTB", "IDFC First Bank"),
    ("RBLBANK", "RBL Bank"),
    ("FEDERALBNK", "Federal Bank"),

    # Major Mid & Large Caps
    ("DIVISLAB", "Divis Laboratories"),
    ("BRITANNIA", "Britannia Industries"),
    ("DIXON", "Dixon Technologies"),
    ("APOLLOHOSP", "Apollo Hospitals"),
    ("MAXHEALTH", "Max Healthcare"),
    ("LAURUSLABS", "Laurus Labs"),
    ("POLYCAB", "Polycab India"),
    ("PAGEIND", "Page Industries"),
    ("TRENT", "Trent Ltd"),
    ("ZEEL", "Zee Entertainment"),
    ("ZOMATO", "Zomato"),
    ("NYKAA", "FSN E-Commerce"),
    ("NAUKRI", "Info Edge"),
    ("PERSISTENT", "Persistent Systems"),
    ("CYIENT", "Cyient"),
    ("TECHM", "Tech Mahindra"),
    ("SUZLON", "Suzlon Energy"),
    ("ADANIENSOL", "Adani Energy Solutions"),
    ("ADANIGREEN", "Adani Green Energy"),
    ("ADANITRANS", "Adani Transmission"),
    ("GODREJPROP", "Godrej Properties"),
    ("SOBHA", "Sobha Limited"),
    ("PRESTIGE", "Prestige Estates"),
    ("DLF", "DLF Ltd"),
    ("GPIL", "Go-Infra Properties"),
    ("JIOSTAR", "JioStar"),
    ("RELXPOWER", "Reliance Power"),
    ("KEI", "KEI Industries"),
    ("SRF", "SRF Ltd"),
    ("BALKRISIND", "Balkrishna Industries"),
    ("AARTIIND", "Aarti Industries"),
    ("ALKEM", "Alkem Laboratories"),
    ("AUROPHARMA", "Aurobindo Pharma"),
    ("BLUESTARCO", "Blue Star"),
    ("BIOCON", "Biocon"),
    ("GLENMARK", "Glenmark Pharmaceuticals"),
    ("ZYDUSLIFE", "Zydus Lifesciences"),
    ("LUPIN", "Lupin"),
    ("SANOFI", "Sanofi India"),
    ("USGIND", "USG India"),
    ("MANYAVAR", "Amul Manyavar"),
    ("RELAXO", "Relaxo Footwears"),
    ("ABFRL", "Aditya Birla Fashion"),
    ("RAYMOND", "Raymond Ltd"),
    ("MOTHERSON", "Samvardhana Motherson"),
    ("BOSCHLTD", "Bosch Ltd"),
    ("VOLTAS", "Voltas"),
    ("WHIRLPOOL", "Whirlpool of India"),
    ("CROMPTON", "Crompton Greaves"),
    ("EBELT", "Ebelt"),
    ("NHPC", "NHPC Ltd"),
    ("POWERINDIA", "Hitachi Power"),
    ("CUMMINSIND", "Cummins India"),
    ("SCHNEIDER", "Schneider Electric"),
    ("MCDOWELL-N", "United Spirits"),
    ("UNITDSPR", "United Spirits"),
    ("MUTHOOTFIN", "Muthoot Finance"),
    ("SHRIRAMFIN", "Shriram Finance"),
    ("BAJAJFINSV", "Bajaj Finserv"),
    ("BAJAJHLDNG", "Bajaj Holdings"),
    ("SBILIFE", "SBI Life Insurance"),
    ("HDFCLIFE", "HDFC Life Insurance"),
    ("ICICIPRULI", "ICICI Prudential Life"),
    ("LICHSGRE", "Life Insurance Corp"),
    ("SBICARD", "SBI Card"),
    ("CHOLAFIN", "Cholamandalam Investment"),
    ("MANAPPURAM", "Manappuram Finance"),
    ("PNBGILDS", "PNB Gilts"),
    ("CHERANPGTN", "Cheran Power"),
    ("ESCORTS", "Escorts Kubota"),
    ("MAZDOCK", "Mazagon Dock"),
    ("COCHINSHIP", "Cochin Shipyard"),
    ("COREWOOD", "Core Wood"),
    ("COROMANDEL", "Coromandel International"),
    ("PIDILITIND", "Pidilite Industries"),
    ("PIIND", "PI Industries"),
    ("BERGEPAINT", "Berger Paints"),
    ("CARBORUNIV", "Carborundum Universal"),
    ("JKCEMENT", "JK Cement"),
    ("ACC", "ACC Ltd"),
    ("SHREECEM", "Shree Cement"),
    ("APLAPOLLO", "APL Apollo Tubes"),
    ("SAIL", "Steel Authority of India"),
    ("JINDALSTEL", "Jindal Steel & Power"),
    ("NMDC", "NMDC Ltd"),
    ("HINDZINC", "Hindustan Zinc"),
    ("JSL", "Jindal Stainless"),
    ("PFC", "Power Finance Corp"),
    ("RECLTD", "REC Ltd"),
    ("MGL", "Mahanagar Gas"),
    ("OIL", "Oil India"),
    ("BPCL", "Bharat Petroleum"),
    ("HPCL", "Hindustan Petroleum"),
    ("IOCL", "Indian Oil Corp"),
    ("NTPC", "NTPC Ltd"),
    ("POWERGRID", "Power Grid Corp"),
    ("NHPC", "NHPC Ltd"),
    ("SJVN", "SJVN Ltd"),
    ("RENL", "Renuka Mills"),
    ("CESC", "CESC Ltd"),
    ("TATAPOWER", "Tata Power"),
    ("ADANIPOWER", "Adani Power"),
    ("TORNTPOWER", "Torrent Power"),
    ("JSWENERGY", "JSW Energy"),
    ("JSWSTEEL", "JSW Steel"),
    ("HAL", "Hindustan Aeronautics"),
    ("BEL", "Bharat Electronics"),
    ("MTARTECH", "MTAR Technologies"),
    ("MAZDOCK", "Mazagon Dock"),
    ("COCHINSHIP", "Cochin Shipyard"),

    # Banking & Finance
    ("UBI", "Union Bank of India"),
    ("IOB", "Indian Overseas Bank"),
    ("YESBANK", "Yes Bank"),
    ("IDBI", "IDBI Bank"),
    ("PNB", "Punjab National Bank"),
    ("BOB", "Bank of Baroda"),
    ("CANBK", "Canara Bank"),
    ("UNIONBANK", "Union Bank of India"),
    ("INDIANB", "Indian Bank"),
    ("BARODODA", "Bank of Baroda"),
    ("CSBBANK", "Central Bank of India"),
    ("FEDERALBNK", "Federal Bank"),
    ("KTKBANK", "Karnataka Bank"),
    ("J&KBANK", "J&K Bank"),
    ("SOUTHBANK", "South Indian Bank"),
    ("INDUSINDBK", "IndusInd Bank"),
    ("IDFCFIRSTB", "IDFC First Bank"),
    ("RBLBANK", "RBL Bank"),
    ("BANDHANBNK", "Bandhan Bank"),
    ("AUBANK", "AU Small Finance Bank"),
    ("ESAFSNB", "ESAF Small Finance Bank"),
    ("UJJIVANSFB", "Ujjivan Small Finance Bank"),
    ("FEDERALBNK", "Federal Bank"),
    ("KARURVYSYA", "Karur Vysya Bank"),
    ("COOPERATBN", "Co-operative Bank"),
    ("CHENNPETRO", "Chennai Petroleum"),
    ("CHOLAHLDNG", "Cholamandalam Holdings"),
    ("MUTHOOTFIN", "Muthoot Finance"),
    ("SHRIRAMFIN", "Shriram Finance"),
    ("BAJAJFINSV", "Bajaj Finserv"),
    ("BAJAJHLDNG", "Bajaj Holdings"),
    ("SBILIFE", "SBI Life Insurance"),
    ("HDFCLIFE", "HDFC Life Insurance"),
    ("ICICIPRULI", "ICICI Prudential Life"),
    ("LICHSGRE", "Life Insurance Corp"),
    ("SBICARD", "SBI Card"),
    ("CHOLAFIN", "Cholamandalam Investment"),
    ("MANAPPURAM", "Manappuram Finance"),
    ("PNBGILDS", "PNB Gilts"),
    ("CHERANPGTN", "Cheran Power"),
    ("M&MFIN", "M&M Financial Services"),
    ("MUTHOOTFIN", "Muthoot Finance"),
    ("SHRIRAMFIN", "Shriram Finance"),
    ("BAJAJFINSV", "Bajaj Finserv"),
    ("BAJAJHLDNG", "Bajaj Holdings"),
    ("SBILIFE", "SBI Life Insurance"),
    ("HDFCLIFE", "HDFC Life Insurance"),
    ("ICICIPRULI", "ICICI Prudential Life"),
    ("LICHSGRE", "Life Insurance Corp"),
    ("SBICARD", "SBI Card"),
    ("CHOLAFIN", "Cholamandalam Investment"),
    ("MANAPPURAM", "Manappuram Finance"),
    ("PNBGILDS", "PNB Gilts"),
    ("CHERANPGTN", "Cheran Power"),
    ("M&MFIN", "M&M Financial Services"),

    # Infrastructure & Engineering
    ("L& T", "Larsen & Toubro"),
    ("LTIM", "LTIMindtree"),
    ("TATAELXSI", "Tata Elxsi"),
    ("CYIENT", "Cyient"),
    ("KPITTECH", "KPIT Technologies"),
    ("SONACOMS", "Sona BLW Precision"),
    ("UNOMINDA", "Uno Minda"),
    ("ESCORTS", "Escorts Kubota"),
    ("GUJGASLTD", "Gujarat Gas"),
    ("IGL", "Indraprastha Gas"),
    ("PETRONET", "Petronet LNG"),
    ("OIL", "Oil India"),
    ("HINDZINC", "Hindustan Zinc"),
    ("NATIONALUM", "National Aluminium"),
    ("GNFC", "Gujarat Narmada Valley Fert"),
    ("CHAMBLFERT", "Chambal Fertilisers"),
    ("COROMANDEL", "Coromandel International"),
    ("BALRAMCHIN", "Balrampur Chini Mills"),
    ("LAURUSLABS", "Laurus Labs"),
    ("GLENMARK", "Glenmark Pharmaceuticals"),
    ("IPCALAB", "Ipca Laboratories"),
    ("AJANTPHARM", "Ajanta Pharma"),
    ("METROPOLIS", "Metropolis Healthcare"),
    ("LALPATHLAB", "Dr Lal PathLabs"),

    # Auto & Auto Components
    ("MARUTI", "Maruti Suzuki India"),
    ("TATAMOTORS", "Tata Motors"),
    ("M&M", "Mahindra & Mahindra"),
    ("HEROMOTOCO", "Hero MotoCorp"),
    ("EICHERMOT", "Eicher Motors"),
    ("TVSMOTOR", "TVS Motor Company"),
    ("BALKRISIND", "Balkrishna Industries"),
    ("MRF", "MRF Ltd"),
    ("BOSCHLTD", "Bosch Ltd"),
    ("MOTHERSON", "Samvardhana Motherson"),
    ("BHARATFORG", "Bharat Forge"),
    ("TIINDIA", "Tube Investments of India"),
    ("APOLLOTYRE", "Apollo Tyres"),
    ("CEAT", "CEAT Ltd"),
    ("JKTYRE", "JK Tyre"),
    ("BRIDGESTONE", "Bridgestone India"),
    ("MICROMAX", "Micromax"),
    ("SONACOMS", "Sona BLW Precision"),
    ("EXIDEIND", "Exide Industries"),
    ("HATHWAY", "Hathway Cable"),
    ("DOW", "Dow Chemical"),
    ("SMLISUZU", "SML Isuzu"),
    ("ASHOKLEY", "Ashok Leyland"),
    ("JAYNECO", "Jaypee Construction"),
    ("SYMPHONY", "Symphony"),
    ("SUPREMEIND", "Supreme Industries"),
    ("GODREJPKG", "Godrej Packaging"),
    ("RALLIS", "Rallis India"),
    ("UPL", "UPL Ltd"),
    ("NAVINFLUOR", "Navin Fluorine"),
    ("SUNDARMFIN", "Sundaram Finance"),
    ("SUNDARMHSV", "Sundaram Harvest"),
    ("TATAPOWER", "Tata Power"),
    ("ADANIPOWER", "Adani Power"),
    ("TORNTPOWER", "Torrent Power"),
    ("JSWENERGY", "JSW Energy"),
    ("NTPC", "NTPC Ltd"),
    ("POWERGRID", "Power Grid Corp"),
    ("NHPC", "NHPC Ltd"),
    ("SJVN", "SJVN Ltd"),
    ("RENL", "Renuka Mills"),
    ("CESC", "CESC Ltd"),
    ("PFC", "Power Finance Corp"),
    ("RECLTD", "REC Ltd"),
    ("MGL", "Mahanagar Gas"),
    ("OIL", "Oil India"),
    ("IOC", "Indian Oil Corp"),
    ("BPCL", "Bharat Petroleum"),
    ("HPCL", "Hindustan Petroleum"),
    ("IOCL", "Indian Oil Corp"),
    ("GAIL", "GAIL India"),
    ("INDIGO", "InterGlobe Aviation"),
    ("CONCOR", "Container Corp of India"),
    ("GMRAIRPORT", "GMR Airports"),
    ("ASTRAL", "Astral Ltd"),
    ("SUPREMEIND", "Supreme Industries"),
    ("SUZLON", "Suzlon Energy"),
    ("BSE", "BSE Ltd"),
    ("CDSL", "Central Depository Services"),
    ("ANGELONE", "Angel One"),
    ("HDFCAMC", "HDFC Asset Management"),
    ("360ONE", "360 One WAM"),
    ("KPITTECH", "KPIT Technologies"),
    ("TATAELXSI", "Tata Elxsi"),
    ("CYIENT", "Cyient"),
    ("SONACOMS", "Sona BLW Precision"),
    ("UNOMINDA", "Uno Minda"),
    ("ESCORTS", "Escorts Kubota"),
    ("GUJGASLTD", "Gujarat Gas"),
    ("IGL", "Indraprastha Gas"),
    ("PETRONET", "Petronet LNG"),
    ("OIL", "Oil India"),
    ("HINDZINC", "Hindustan Zinc"),
    ("NATIONALUM", "National Aluminium"),
    ("GNFC", "Gujarat Narmada Valley Fert"),
    ("CHAMBLFERT", "Chambal Fertilisers"),
    ("COROMANDEL", "Coromandel International"),
    ("BALRAMCHIN", "Balrampur Chini Mills"),
    ("LAURUSLABS", "Laurus Labs"),
    ("GLENMARK", "Glenmark Pharmaceuticals"),
    ("IPCALAB", "Ipca Laboratories"),
    ("AJANTPHARM", "Ajanta Pharma"),
    ("METROPOLIS", "Metropolis Healthcare"),
    ("LALPATHLAB", "Dr Lal PathLabs"),
]


def _kind(symbol: str) -> str:
    return "index" if symbol in {s for s, _ in INDICES} else "stock"


def all_instruments() -> list[dict]:
    """Full searchable list: indices first, then equities."""
    out: list[dict] = [{"symbol": s, "name": n, "kind": "index"} for s, n in INDICES]
    out += [{"symbol": s, "name": n, "kind": "stock"} for s, n in STOCKS]
    return out


def search(query: str, limit: int = 20) -> list[dict]:
    """Rank instruments against a query. Exact/prefix symbol matches win, then
    word-prefix name matches, then loose substring matches."""
    q = query.strip().lower()
    if not q:
        return all_instruments()[:limit]

    scored: list[tuple[int, dict]] = []
    for inst in all_instruments():
        sym = inst["symbol"].lower()
        name = inst["name"].lower()
        score = _score(q, sym, name)
        if score > 0:
            scored.append((score, inst))
    scored.sort(key=lambda x: (-x[0], x[1]["symbol"]))
    return [inst for _, inst in scored[:limit]]


def _score(q: str, sym: str, name: str) -> int:
    if sym == q:
        return 100
    if sym.startswith(q):
        return 90
    # any word in the company name starting with the query
    if any(w.startswith(q) for w in name.replace("&", " ").split()):
        return 70
    if q in sym:
        return 50
    if q in name:
        return 40
    return 0
